-- Initial unreleased schema, generated by tools/generate_migrations.py.
-- Execute statements under the migration runner exclusive lock.

CREATE TABLE schema_migrations (
    version BIGINT NOT NULL,
    name VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    checksum VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    state VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    started_at BIGINT NOT NULL,
    completed_at BIGINT,
    last_step BIGINT NOT NULL,
    error_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin,
    PRIMARY KEY (version),
    CHECK (state IN ('applying','applied','failed')),
    CHECK (length(name) <= 128),
    CHECK (length(checksum) = 64),
    CHECK (length(state) <= 32),
    CHECK (last_step >= 0),
    CHECK (length(error_code) <= 64)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
