-- Initial unreleased schema, generated by tools/generate_migrations.py.
-- Execute statements under the migration runner exclusive lock.

CREATE TABLE schema_migrations (
    version INTEGER NOT NULL,
    name TEXT NOT NULL,
    checksum TEXT NOT NULL,
    state TEXT NOT NULL,
    started_at INTEGER NOT NULL,
    completed_at INTEGER,
    last_step INTEGER NOT NULL,
    error_code TEXT,
    PRIMARY KEY (version),
    CHECK (state IN ('applying','applied','failed')),
    CHECK (length(name) <= 128),
    CHECK (length(checksum) = 64),
    CHECK (length(state) <= 32),
    CHECK (last_step >= 0),
    CHECK (length(error_code) <= 64)
);
