-- Initial unreleased schema, generated by tools/generate_migrations.py.
-- Execute statements under the migration runner exclusive lock.

CREATE TABLE accounts (
    id TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    version INTEGER NOT NULL,
    login_name TEXT NOT NULL,
    normalized_login_name TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    state TEXT NOT NULL,
    auth_epoch INTEGER NOT NULL,
    is_global_admin INTEGER NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (normalized_login_name),
    CHECK (state IN ('active','reset_pending','disabled')),
    CHECK (length(id) = 36),
    CHECK (version >= 0),
    CHECK (length(login_name) <= 64),
    CHECK (length(normalized_login_name) <= 64),
    CHECK (length(state) <= 32),
    CHECK (auth_epoch >= 0),
    CHECK (is_global_admin IN (0,1))
);

CREATE TABLE sessions (
    id TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    token_hash TEXT NOT NULL,
    account_id TEXT NOT NULL,
    auth_epoch INTEGER NOT NULL,
    last_seen_at INTEGER NOT NULL,
    absolute_expires_at INTEGER NOT NULL,
    csrf_secret_hash TEXT NOT NULL,
    CONSTRAINT fk_e6ecfa1b08e031d3 FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE RESTRICT,
    PRIMARY KEY (id),
    UNIQUE (token_hash),
    CHECK (length(id) = 36),
    CHECK (length(token_hash) = 64),
    CHECK (length(account_id) = 36),
    CHECK (auth_epoch >= 0),
    CHECK (length(csrf_secret_hash) = 64)
);

CREATE TABLE password_reset_tokens (
    id TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    token_hash TEXT NOT NULL,
    account_id TEXT NOT NULL,
    auth_epoch INTEGER NOT NULL,
    expires_at INTEGER NOT NULL,
    consumed_at INTEGER,
    invalidated_at INTEGER,
    CONSTRAINT fk_7ca2880fc42e636f FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE RESTRICT,
    PRIMARY KEY (id),
    UNIQUE (token_hash),
    CHECK (length(id) = 36),
    CHECK (length(token_hash) = 64),
    CHECK (length(account_id) = 36),
    CHECK (auth_epoch >= 0)
);

CREATE TABLE auth_rate_limits (
    id TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    kind TEXT NOT NULL,
    subject_hash TEXT NOT NULL,
    window_start INTEGER NOT NULL,
    failure_count INTEGER NOT NULL,
    blocked_until INTEGER,
    PRIMARY KEY (id),
    UNIQUE (kind, subject_hash, window_start),
    CHECK (length(id) = 36),
    CHECK (length(kind) <= 32),
    CHECK (length(subject_hash) = 64),
    CHECK (failure_count >= 0)
);

CREATE TABLE service_settings (
    id INTEGER NOT NULL,
    schema_version INTEGER NOT NULL,
    settings_json TEXT NOT NULL,
    updated_at INTEGER NOT NULL,
    version INTEGER NOT NULL,
    updated_by TEXT,
    CONSTRAINT fk_ec052263cb7d9e19 FOREIGN KEY (updated_by) REFERENCES accounts (id) ON DELETE RESTRICT,
    PRIMARY KEY (id),
    CHECK (id = 1),
    CHECK (schema_version >= 0),
    CHECK (version >= 0),
    CHECK (length(updated_by) = 36)
);
