-- Initial unreleased schema, generated by tools/generate_migrations.py.
-- Execute statements under the migration runner exclusive lock.

CREATE TABLE key_materials (
    id TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    spki_sha256 TEXT NOT NULL,
    spki_der BLOB NOT NULL,
    algorithm TEXT NOT NULL,
    parameters_json TEXT NOT NULL,
    origin TEXT NOT NULL,
    compromised_at INTEGER,
    PRIMARY KEY (id),
    UNIQUE (spki_sha256),
    CHECK (origin IN ('generated','imported')),
    CHECK (length(id) = 36),
    CHECK (length(spki_sha256) = 64),
    CHECK (length(algorithm) <= 32),
    CHECK (length(origin) <= 32)
);

CREATE TABLE encryption_generations (
    id TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    activated_at INTEGER NOT NULL,
    retired_at INTEGER,
    PRIMARY KEY (id),
    CHECK (length(id) = 36)
);

CREATE TABLE private_key_secrets (
    key_material_id TEXT NOT NULL,
    purpose TEXT NOT NULL,
    encryption_generation_id TEXT NOT NULL,
    format_version INTEGER NOT NULL,
    nonce BLOB NOT NULL,
    ciphertext BLOB NOT NULL,
    CONSTRAINT fk_c503ce84bd038410 FOREIGN KEY (key_material_id) REFERENCES key_materials (id) ON DELETE RESTRICT,
    CONSTRAINT fk_50bdad5b462c1da6 FOREIGN KEY (encryption_generation_id) REFERENCES encryption_generations (id) ON DELETE RESTRICT,
    PRIMARY KEY (key_material_id),
    CHECK (purpose IN ('ca_signing','leaf_delivery','internal_tls','bootstrap_ca')),
    CHECK (length(nonce) = 12),
    CHECK (length(key_material_id) = 36),
    CHECK (length(purpose) <= 32),
    CHECK (length(encryption_generation_id) = 36),
    CHECK (format_version >= 0)
);

CREATE TABLE encryption_verifier (
    id INTEGER NOT NULL,
    encryption_generation_id TEXT NOT NULL,
    format_version INTEGER NOT NULL,
    nonce BLOB NOT NULL,
    ciphertext BLOB NOT NULL,
    CONSTRAINT fk_21d142aa3402a788 FOREIGN KEY (encryption_generation_id) REFERENCES encryption_generations (id) ON DELETE RESTRICT,
    PRIMARY KEY (id),
    CHECK (id = 1),
    CHECK (length(nonce) = 12),
    CHECK (length(encryption_generation_id) = 36),
    CHECK (format_version >= 0)
);
