-- Initial unreleased schema, generated by tools/generate_migrations.py.
-- Execute statements under the migration runner exclusive lock.

CREATE TABLE ca_transitions (
    id TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    version INTEGER NOT NULL,
    source_authority_id TEXT NOT NULL,
    target_authority_id TEXT,
    mode TEXT NOT NULL,
    state TEXT NOT NULL,
    reported_by TEXT NOT NULL,
    reported_at INTEGER NOT NULL,
    reason TEXT NOT NULL,
    CONSTRAINT fk_f26514908e99e611 FOREIGN KEY (source_authority_id) REFERENCES authorities (id) ON DELETE RESTRICT,
    CONSTRAINT fk_48f8f15fcb21dc55 FOREIGN KEY (target_authority_id) REFERENCES authorities (id) ON DELETE RESTRICT,
    CONSTRAINT fk_ec18d862ee114439 FOREIGN KEY (reported_by) REFERENCES accounts (id) ON DELETE RESTRICT,
    PRIMARY KEY (id),
    CHECK (mode IN ('normal','emergency')),
    CHECK (state IN ('in_progress','externally_completed','closed')),
    CHECK (target_authority_id IS NULL OR target_authority_id <> source_authority_id),
    CHECK (length(id) = 36),
    CHECK (version >= 0),
    CHECK (length(source_authority_id) = 36),
    CHECK (length(target_authority_id) = 36),
    CHECK (length(mode) <= 32),
    CHECK (length(state) <= 32),
    CHECK (length(reported_by) = 36)
);

CREATE TABLE transition_impacts (
    transition_id TEXT NOT NULL,
    certificate_id TEXT NOT NULL,
    replacement_certificate_id TEXT,
    reissued_at INTEGER,
    CONSTRAINT fk_13579f0c61de6da2 FOREIGN KEY (transition_id) REFERENCES ca_transitions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_62cd53a17ff95231 FOREIGN KEY (certificate_id) REFERENCES certificates (id) ON DELETE RESTRICT,
    CONSTRAINT fk_a5ab2d2e43b207d2 FOREIGN KEY (replacement_certificate_id) REFERENCES certificates (id) ON DELETE RESTRICT,
    PRIMARY KEY (transition_id, certificate_id),
    CHECK (length(transition_id) = 36),
    CHECK (length(certificate_id) = 36),
    CHECK (length(replacement_certificate_id) = 36)
);

CREATE TABLE deployment_confirmations (
    id TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    transition_id TEXT NOT NULL,
    certificate_id TEXT,
    target_label TEXT NOT NULL,
    action TEXT NOT NULL,
    confirmed_by TEXT,
    confirmed_at INTEGER,
    CONSTRAINT fk_3eeaaec4c2e7075a FOREIGN KEY (transition_id) REFERENCES ca_transitions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_a5f7e7ea535212e4 FOREIGN KEY (certificate_id) REFERENCES certificates (id) ON DELETE RESTRICT,
    CONSTRAINT fk_ab1c0a331eafeae1 FOREIGN KEY (confirmed_by) REFERENCES accounts (id) ON DELETE RESTRICT,
    PRIMARY KEY (id),
    CHECK (action IN ('trust_added','certificate_installed','trust_removed')),
    CHECK (length(id) = 36),
    CHECK (length(transition_id) = 36),
    CHECK (length(certificate_id) = 36),
    CHECK (length(action) <= 32),
    CHECK (length(confirmed_by) = 36)
);

CREATE TABLE tls_versions (
    id TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    source TEXT NOT NULL,
    key_material_id TEXT NOT NULL,
    managed_certificate_id TEXT,
    leaf_der BLOB NOT NULL,
    chain_bundle BLOB NOT NULL,
    validated_service_url TEXT,
    not_after INTEGER NOT NULL,
    CONSTRAINT fk_d39c076d76798d02 FOREIGN KEY (key_material_id) REFERENCES key_materials (id) ON DELETE RESTRICT,
    CONSTRAINT fk_939d8acf0a6cf0e4 FOREIGN KEY (managed_certificate_id) REFERENCES leaf_certificates (certificate_id) ON DELETE RESTRICT,
    PRIMARY KEY (id),
    CHECK (source IN ('bootstrap','managed','external')),
    CHECK (source = 'bootstrap' OR validated_service_url IS NOT NULL),
    CHECK (length(id) = 36),
    CHECK (length(source) <= 32),
    CHECK (length(key_material_id) = 36),
    CHECK (length(managed_certificate_id) = 36)
);

CREATE TABLE tls_changes (
    id TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    version INTEGER NOT NULL,
    previous_version_id TEXT,
    candidate_version_id TEXT NOT NULL,
    phase TEXT NOT NULL,
    error_code TEXT,
    CONSTRAINT fk_cf4e012859ecc8c7 FOREIGN KEY (previous_version_id) REFERENCES tls_versions (id) ON DELETE RESTRICT,
    CONSTRAINT fk_88007c99f5dbcca7 FOREIGN KEY (candidate_version_id) REFERENCES tls_versions (id) ON DELETE RESTRICT,
    PRIMARY KEY (id),
    CHECK (phase IN ('prepared','committed','applied','rolled_back','recovery_required')),
    CHECK (length(id) = 36),
    CHECK (version >= 0),
    CHECK (length(previous_version_id) = 36),
    CHECK (length(candidate_version_id) = 36),
    CHECK (length(phase) <= 32),
    CHECK (length(error_code) <= 64)
);

CREATE TABLE maintenance_runs (
    id TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    version INTEGER NOT NULL,
    kind TEXT NOT NULL,
    phase TEXT NOT NULL,
    details_json TEXT NOT NULL,
    started_at INTEGER NOT NULL,
    completed_at INTEGER,
    error_code TEXT,
    PRIMARY KEY (id),
    CHECK (length(id) = 36),
    CHECK (version >= 0),
    CHECK (length(kind) <= 32),
    CHECK (length(phase) <= 32),
    CHECK (length(error_code) <= 64)
);

CREATE TABLE maintenance_crl_requirements (
    maintenance_run_id TEXT NOT NULL,
    ca_key_generation_id TEXT NOT NULL,
    minimum_generation INTEGER NOT NULL,
    minimum_number_hex TEXT NOT NULL,
    satisfied_crl_id TEXT,
    CONSTRAINT fk_7c43436d8aad7b50 FOREIGN KEY (maintenance_run_id) REFERENCES maintenance_runs (id) ON DELETE RESTRICT,
    CONSTRAINT fk_07fe1d5c42134a95 FOREIGN KEY (ca_key_generation_id) REFERENCES ca_key_generations (id) ON DELETE RESTRICT,
    CONSTRAINT fk_833e3eb8305242b1 FOREIGN KEY (satisfied_crl_id) REFERENCES crl_documents (id) ON DELETE RESTRICT,
    PRIMARY KEY (maintenance_run_id, ca_key_generation_id),
    CHECK (length(maintenance_run_id) = 36),
    CHECK (length(ca_key_generation_id) = 36),
    CHECK (minimum_generation >= 0),
    CHECK (length(minimum_number_hex) BETWEEN 1 AND 40),
    CHECK ((length(minimum_number_hex) = 1 OR substr(minimum_number_hex,1,1) <> '0')),
    CHECK (minimum_number_hex NOT GLOB '*[^0-9a-f]*'),
    CHECK (length(satisfied_crl_id) = 36)
);

CREATE TABLE jobs (
    id TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    version INTEGER NOT NULL,
    kind TEXT NOT NULL,
    dedup_key TEXT NOT NULL,
    payload_version INTEGER NOT NULL,
    payload_json TEXT NOT NULL,
    state TEXT NOT NULL,
    available_at INTEGER NOT NULL,
    lease_until INTEGER,
    attempt_count INTEGER NOT NULL,
    last_error_code TEXT,
    PRIMARY KEY (id),
    UNIQUE (dedup_key),
    CHECK (state IN ('pending','running','succeeded','failed')),
    CHECK (length(id) = 36),
    CHECK (version >= 0),
    CHECK (length(kind) <= 32),
    CHECK (length(dedup_key) <= 128),
    CHECK (payload_version >= 0),
    CHECK (length(state) <= 32),
    CHECK (attempt_count >= 0),
    CHECK (length(last_error_code) <= 64)
);
