-- Initial unreleased schema, generated by tools/generate_migrations.py.
-- Execute statements under the migration runner exclusive lock.

CREATE TABLE installation (
    id INTEGER NOT NULL,
    setup_stage TEXT NOT NULL,
    first_admin_id TEXT,
    active_encryption_generation_id TEXT NOT NULL,
    active_tls_version_id TEXT,
    service_mode TEXT NOT NULL,
    updated_at INTEGER NOT NULL,
    version INTEGER NOT NULL,
    CONSTRAINT fk_880580b880d4c5c0 FOREIGN KEY (first_admin_id) REFERENCES accounts (id) ON DELETE RESTRICT,
    CONSTRAINT fk_686eed8d14e369c4 FOREIGN KEY (active_encryption_generation_id) REFERENCES encryption_generations (id) ON DELETE RESTRICT,
    CONSTRAINT fk_b2c4347c9d58aec8 FOREIGN KEY (active_tls_version_id) REFERENCES tls_versions (id) ON DELETE RESTRICT,
    PRIMARY KEY (id),
    CHECK (id = 1),
    CHECK (setup_stage IN ('account_required','pki_required','complete')),
    CHECK (service_mode IN ('starting','serving','maintenance','recovery_required')),
    CHECK ((setup_stage = 'account_required' AND first_admin_id IS NULL) OR (setup_stage <> 'account_required' AND first_admin_id IS NOT NULL)),
    CHECK (length(setup_stage) <= 32),
    CHECK (length(first_admin_id) = 36),
    CHECK (length(active_encryption_generation_id) = 36),
    CHECK (length(active_tls_version_id) = 36),
    CHECK (length(service_mode) <= 32),
    CHECK (version >= 0)
);

CREATE TABLE audit_events (
    id TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    occurred_at INTEGER NOT NULL,
    actor_kind TEXT NOT NULL,
    actor_id TEXT,
    token_id TEXT,
    action TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id TEXT,
    client_ip TEXT,
    result TEXT NOT NULL,
    details_json TEXT NOT NULL,
    PRIMARY KEY (id),
    CHECK (actor_kind IN ('account','download_token','cli','system','anonymous')),
    CHECK (result IN ('success','failure')),
    CHECK (length(id) = 36),
    CHECK (length(actor_kind) <= 32),
    CHECK (length(actor_id) = 36),
    CHECK (length(token_id) = 36),
    CHECK (length(action) <= 64),
    CHECK (length(target_type) <= 64),
    CHECK (length(target_id) = 36),
    CHECK (length(client_ip) <= 64),
    CHECK (length(result) <= 32)
);

CREATE TABLE audit_event_scopes (
    event_id TEXT NOT NULL,
    authority_id TEXT NOT NULL,
    CONSTRAINT fk_a026aa649a1fe328 FOREIGN KEY (event_id) REFERENCES audit_events (id) ON DELETE RESTRICT,
    CONSTRAINT fk_0b6ca9f7b2fa06be FOREIGN KEY (authority_id) REFERENCES authorities (id) ON DELETE RESTRICT,
    PRIMARY KEY (event_id, authority_id),
    CHECK (length(event_id) = 36),
    CHECK (length(authority_id) = 36)
);

CREATE INDEX ix_certificates_1 ON certificates (not_after,id);

CREATE INDEX ix_certificates_2 ON certificates (issuer_ca_key_generation_id,not_after);

CREATE INDEX ix_certificates_3 ON certificates (key_material_id,id);

CREATE INDEX ix_leaf_certificates_1 ON leaf_certificates (series_id,certificate_id);

CREATE INDEX ix_certificate_sans_1 ON certificate_sans (type,normalized_value_hash);

CREATE INDEX ix_key_deliveries_1 ON key_deliveries (state,expires_at);

CREATE INDEX ix_download_tokens_1 ON download_tokens (key_delivery_id,invalidated_at);

CREATE INDEX ix_download_tokens_2 ON download_tokens (certificate_id,purpose,invalidated_at);

CREATE INDEX ix_download_tokens_3 ON download_tokens (expires_at);

CREATE INDEX ix_sessions_1 ON sessions (account_id,absolute_expires_at);

CREATE INDEX ix_password_reset_tokens_1 ON password_reset_tokens (account_id,expires_at);

CREATE INDEX ix_jobs_1 ON jobs (state,available_at);

CREATE INDEX ix_audit_events_1 ON audit_events (occurred_at,id);

CREATE INDEX ix_audit_events_2 ON audit_events (actor_id,occurred_at);

CREATE INDEX ix_audit_events_3 ON audit_events (client_ip,occurred_at);

CREATE INDEX ix_audit_event_scopes_1 ON audit_event_scopes (authority_id,event_id);

CREATE INDEX ix_crl_documents_1 ON crl_documents (ca_key_generation_id,created_at);

CREATE INDEX ix_revocations_1 ON revocations (certificate_id);

CREATE INDEX ix_ca_takeovers_1 ON ca_takeovers (ca_key_generation_id,state);
