-- Initial unreleased schema, generated by tools/generate_migrations.py.
-- Execute statements under the migration runner exclusive lock.

CREATE TABLE schema_migrations (
    version BIGINT NOT NULL,
    name VARCHAR(128) COLLATE "C" NOT NULL,
    checksum VARCHAR(64) COLLATE "C" NOT NULL,
    state VARCHAR(32) COLLATE "C" NOT NULL,
    started_at BIGINT NOT NULL,
    completed_at BIGINT,
    last_step BIGINT NOT NULL,
    error_code VARCHAR(64) COLLATE "C",
    PRIMARY KEY (version),
    CHECK (state IN ('applying','applied','failed')),
    CHECK (length(name) <= 128),
    CHECK (length(checksum) = 64),
    CHECK (length(state) <= 32),
    CHECK (last_step >= 0),
    CHECK (length(error_code) <= 64)
);
