-- Initial unreleased schema, generated by tools/generate_migrations.py.
-- Execute statements under the migration runner exclusive lock.

CREATE TABLE authorities (
    id VARCHAR(36) COLLATE "C" NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    version BIGINT NOT NULL,
    kind VARCHAR(32) COLLATE "C" NOT NULL,
    name TEXT NOT NULL,
    management_parent_id VARCHAR(36) COLLATE "C",
    issuance_state VARCHAR(32) COLLATE "C" NOT NULL,
    issuance_certificate_id VARCHAR(36) COLLATE "C",
    archived_at BIGINT,
    PRIMARY KEY (id),
    CHECK (kind IN ('root','intermediate','bootstrap')),
    CHECK (issuance_state IN ('inventory','enabled','stopped')),
    CHECK ((kind = 'intermediate' AND management_parent_id IS NOT NULL) OR (kind IN ('root','bootstrap') AND management_parent_id IS NULL)),
    CHECK (length(id) = 36),
    CHECK (version >= 0),
    CHECK (length(kind) <= 32),
    CHECK (length(management_parent_id) = 36),
    CHECK (length(issuance_state) <= 32),
    CHECK (length(issuance_certificate_id) = 36)
);

CREATE TABLE ca_key_generations (
    id VARCHAR(36) COLLATE "C" NOT NULL,
    created_at BIGINT NOT NULL,
    authority_id VARCHAR(36) COLLATE "C" NOT NULL,
    key_material_id VARCHAR(36) COLLATE "C" NOT NULL,
    generation_no BIGINT NOT NULL,
    key_destroyed_at BIGINT,
    PRIMARY KEY (id),
    UNIQUE (authority_id, generation_no),
    UNIQUE (key_material_id),
    CHECK (length(id) = 36),
    CHECK (length(authority_id) = 36),
    CHECK (length(key_material_id) = 36),
    CHECK (generation_no >= 0)
);

CREATE TABLE certificates (
    id VARCHAR(36) COLLATE "C" NOT NULL,
    created_at BIGINT NOT NULL,
    der_sha256 VARCHAR(64) COLLATE "C" NOT NULL,
    der BYTEA NOT NULL,
    key_material_id VARCHAR(36) COLLATE "C" NOT NULL,
    issuer_ca_key_generation_id VARCHAR(36) COLLATE "C" NOT NULL,
    serial_hex VARCHAR(40) COLLATE "C" NOT NULL,
    not_before BIGINT NOT NULL,
    not_after BIGINT NOT NULL,
    subject_json TEXT NOT NULL,
    extensions_json TEXT NOT NULL,
    origin VARCHAR(32) COLLATE "C" NOT NULL,
    created_by VARCHAR(36) COLLATE "C",
    PRIMARY KEY (id),
    UNIQUE (der_sha256),
    UNIQUE (issuer_ca_key_generation_id, serial_hex),
    CHECK (not_after > not_before),
    CHECK (serial_hex <> '0'),
    CHECK (origin IN ('generated','imported')),
    CHECK (length(id) = 36),
    CHECK (length(der_sha256) = 64),
    CHECK (length(key_material_id) = 36),
    CHECK (length(issuer_ca_key_generation_id) = 36),
    CHECK (length(serial_hex) BETWEEN 1 AND 40),
    CHECK ((length(serial_hex) = 1 OR substr(serial_hex,1,1) <> '0')),
    CHECK (serial_hex ~ '^[0-9a-f]+$'),
    CHECK (length(origin) <= 32),
    CHECK (length(created_by) = 36)
);

CREATE TABLE ca_certificates (
    certificate_id VARCHAR(36) COLLATE "C" NOT NULL,
    ca_key_generation_id VARCHAR(36) COLLATE "C" NOT NULL,
    issuer_ca_certificate_id VARCHAR(36) COLLATE "C",
    PRIMARY KEY (certificate_id),
    CHECK (length(certificate_id) = 36),
    CHECK (length(ca_key_generation_id) = 36),
    CHECK (length(issuer_ca_certificate_id) = 36)
);

CREATE TABLE leaf_series (
    id VARCHAR(36) COLLATE "C" NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    version BIGINT NOT NULL,
    name TEXT NOT NULL,
    purpose VARCHAR(32) COLLATE "C" NOT NULL,
    management_authority_id VARCHAR(36) COLLATE "C" NOT NULL,
    current_certificate_id VARCHAR(36) COLLATE "C",
    current_key_generation_id VARCHAR(36) COLLATE "C",
    validity_policy_json TEXT NOT NULL,
    rotate_every BIGINT NOT NULL,
    archived_at BIGINT,
    PRIMARY KEY (id),
    CHECK (purpose IN ('distributed','internal_tls','bootstrap_tls')),
    CHECK (rotate_every BETWEEN 1 AND 100),
    CHECK (length(id) = 36),
    CHECK (version >= 0),
    CHECK (length(purpose) <= 32),
    CHECK (length(management_authority_id) = 36),
    CHECK (length(current_certificate_id) = 36),
    CHECK (length(current_key_generation_id) = 36)
);

CREATE TABLE leaf_key_generations (
    id VARCHAR(36) COLLATE "C" NOT NULL,
    created_at BIGINT NOT NULL,
    series_id VARCHAR(36) COLLATE "C" NOT NULL,
    key_material_id VARCHAR(36) COLLATE "C" NOT NULL,
    generation_no BIGINT NOT NULL,
    renewal_count BIGINT NOT NULL,
    prior_history_unknown BOOLEAN NOT NULL,
    custody VARCHAR(32) COLLATE "C" NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (series_id, generation_no),
    CHECK (custody IN ('pending_delivery','client_held','internal')),
    CHECK (length(id) = 36),
    CHECK (length(series_id) = 36),
    CHECK (length(key_material_id) = 36),
    CHECK (generation_no >= 0),
    CHECK (renewal_count >= 0),
    CHECK (length(custody) <= 32)
);

CREATE TABLE leaf_certificates (
    certificate_id VARCHAR(36) COLLATE "C" NOT NULL,
    series_id VARCHAR(36) COLLATE "C" NOT NULL,
    leaf_key_generation_id VARCHAR(36) COLLATE "C" NOT NULL,
    issuer_ca_certificate_id VARCHAR(36) COLLATE "C" NOT NULL,
    previous_certificate_id VARCHAR(36) COLLATE "C",
    operation VARCHAR(32) COLLATE "C" NOT NULL,
    renewal_count_at_issue BIGINT NOT NULL,
    policy_snapshot_json TEXT NOT NULL,
    PRIMARY KEY (certificate_id),
    CHECK (operation IN ('initial','renew','rekey','migrate','emergency','import')),
    CHECK (length(certificate_id) = 36),
    CHECK (length(series_id) = 36),
    CHECK (length(leaf_key_generation_id) = 36),
    CHECK (length(issuer_ca_certificate_id) = 36),
    CHECK (length(previous_certificate_id) = 36),
    CHECK (length(operation) <= 32),
    CHECK (renewal_count_at_issue >= 0)
);

CREATE TABLE certificate_sans (
    certificate_id VARCHAR(36) COLLATE "C" NOT NULL,
    position BIGINT NOT NULL,
    type VARCHAR(32) COLLATE "C" NOT NULL,
    normalized_value TEXT NOT NULL,
    normalized_value_hash VARCHAR(64) COLLATE "C" NOT NULL,
    PRIMARY KEY (certificate_id, position),
    CHECK (length(certificate_id) = 36),
    CHECK (position >= 0),
    CHECK (length(type) <= 32),
    CHECK (length(normalized_value_hash) = 64)
);
