-- Initial unreleased schema, generated by tools/generate_migrations.py.
-- Execute statements under the migration runner exclusive lock.

CREATE TABLE key_deliveries (
    id VARCHAR(36) COLLATE "C" NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    version BIGINT NOT NULL,
    leaf_key_generation_id VARCHAR(36) COLLATE "C" NOT NULL,
    certificate_id VARCHAR(36) COLLATE "C" NOT NULL,
    expires_at BIGINT NOT NULL,
    state VARCHAR(32) COLLATE "C" NOT NULL,
    consumed_at BIGINT,
    finished_at BIGINT,
    failure_code VARCHAR(64) COLLATE "C",
    PRIMARY KEY (id),
    UNIQUE (leaf_key_generation_id),
    UNIQUE (certificate_id),
    CHECK (state IN ('pending','transferring','server_completed','failed','expired')),
    CHECK (state <> 'pending' OR consumed_at IS NULL),
    CHECK (state NOT IN ('transferring','server_completed') OR consumed_at IS NOT NULL),
    CHECK (length(id) = 36),
    CHECK (version >= 0),
    CHECK (length(leaf_key_generation_id) = 36),
    CHECK (length(certificate_id) = 36),
    CHECK (length(state) <= 32),
    CHECK (length(failure_code) <= 64)
);

CREATE TABLE download_tokens (
    id VARCHAR(36) COLLATE "C" NOT NULL,
    created_at BIGINT NOT NULL,
    token_hash VARCHAR(64) COLLATE "C" NOT NULL,
    purpose VARCHAR(32) COLLATE "C" NOT NULL,
    certificate_id VARCHAR(36) COLLATE "C" NOT NULL,
    key_delivery_id VARCHAR(36) COLLATE "C",
    expires_at BIGINT NOT NULL,
    consumed_at BIGINT,
    invalidated_at BIGINT,
    created_by VARCHAR(36) COLLATE "C" NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (token_hash),
    CHECK ((purpose = 'leaf_public' AND key_delivery_id IS NULL) OR (purpose = 'leaf_private' AND key_delivery_id IS NOT NULL)),
    CHECK (length(id) = 36),
    CHECK (length(token_hash) = 64),
    CHECK (length(purpose) <= 32),
    CHECK (length(certificate_id) = 36),
    CHECK (length(key_delivery_id) = 36),
    CHECK (length(created_by) = 36)
);

CREATE TABLE operation_requests (
    id VARCHAR(36) COLLATE "C" NOT NULL,
    created_at BIGINT NOT NULL,
    actor_key VARCHAR(64) COLLATE "C" NOT NULL,
    operation VARCHAR(32) COLLATE "C" NOT NULL,
    request_id VARCHAR(36) COLLATE "C" NOT NULL,
    input_hash VARCHAR(64) COLLATE "C" NOT NULL,
    state VARCHAR(32) COLLATE "C" NOT NULL,
    result_certificate_id VARCHAR(36) COLLATE "C",
    result_json TEXT,
    PRIMARY KEY (id),
    UNIQUE (actor_key, operation, request_id),
    CHECK (state IN ('processing','succeeded','failed')),
    CHECK (length(id) = 36),
    CHECK (length(actor_key) <= 64),
    CHECK (length(operation) <= 32),
    CHECK (length(request_id) = 36),
    CHECK (length(input_hash) = 64),
    CHECK (length(state) <= 32),
    CHECK (length(result_certificate_id) = 36)
);
