-- Initial unreleased schema, generated by tools/generate_migrations.py.
-- Execute statements under the migration runner exclusive lock.

CREATE TABLE installation (
    id BIGINT NOT NULL,
    setup_stage VARCHAR(32) COLLATE "C" NOT NULL,
    first_admin_id VARCHAR(36) COLLATE "C",
    active_encryption_generation_id VARCHAR(36) COLLATE "C" NOT NULL,
    active_tls_version_id VARCHAR(36) COLLATE "C",
    service_mode VARCHAR(32) COLLATE "C" NOT NULL,
    updated_at BIGINT NOT NULL,
    version BIGINT NOT NULL,
    PRIMARY KEY (id),
    CHECK (id = 1),
    CHECK (setup_stage IN ('account_required','pki_required','complete')),
    CHECK (service_mode IN ('starting','serving','maintenance','recovery_required')),
    CHECK ((setup_stage = 'account_required' AND first_admin_id IS NULL) OR (setup_stage <> 'account_required' AND first_admin_id IS NOT NULL)),
    CHECK (length(setup_stage) <= 32),
    CHECK (length(first_admin_id) = 36),
    CHECK (length(active_encryption_generation_id) = 36),
    CHECK (length(active_tls_version_id) = 36),
    CHECK (length(service_mode) <= 32),
    CHECK (version >= 0)
);

CREATE TABLE audit_events (
    id VARCHAR(36) COLLATE "C" NOT NULL,
    created_at BIGINT NOT NULL,
    occurred_at BIGINT NOT NULL,
    actor_kind VARCHAR(32) COLLATE "C" NOT NULL,
    actor_id VARCHAR(36) COLLATE "C",
    token_id VARCHAR(36) COLLATE "C",
    action VARCHAR(64) COLLATE "C" NOT NULL,
    target_type VARCHAR(64) COLLATE "C" NOT NULL,
    target_id VARCHAR(36) COLLATE "C",
    client_ip VARCHAR(64) COLLATE "C",
    result VARCHAR(32) COLLATE "C" NOT NULL,
    details_json TEXT NOT NULL,
    PRIMARY KEY (id),
    CHECK (actor_kind IN ('account','download_token','cli','system','anonymous')),
    CHECK (result IN ('success','failure')),
    CHECK (length(id) = 36),
    CHECK (length(actor_kind) <= 32),
    CHECK (length(actor_id) = 36),
    CHECK (length(token_id) = 36),
    CHECK (length(action) <= 64),
    CHECK (length(target_type) <= 64),
    CHECK (length(target_id) = 36),
    CHECK (length(client_ip) <= 64),
    CHECK (length(result) <= 32)
);

CREATE TABLE audit_event_scopes (
    event_id VARCHAR(36) COLLATE "C" NOT NULL,
    authority_id VARCHAR(36) COLLATE "C" NOT NULL,
    PRIMARY KEY (event_id, authority_id),
    CHECK (length(event_id) = 36),
    CHECK (length(authority_id) = 36)
);

ALTER TABLE sessions ADD CONSTRAINT fk_e6ecfa1b08e031d3 FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE RESTRICT;

ALTER TABLE password_reset_tokens ADD CONSTRAINT fk_7ca2880fc42e636f FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE RESTRICT;

ALTER TABLE service_settings ADD CONSTRAINT fk_ec052263cb7d9e19 FOREIGN KEY (updated_by) REFERENCES accounts (id) ON DELETE RESTRICT;

ALTER TABLE private_key_secrets ADD CONSTRAINT fk_c503ce84bd038410 FOREIGN KEY (key_material_id) REFERENCES key_materials (id) ON DELETE RESTRICT;

ALTER TABLE private_key_secrets ADD CONSTRAINT fk_50bdad5b462c1da6 FOREIGN KEY (encryption_generation_id) REFERENCES encryption_generations (id) ON DELETE RESTRICT;

ALTER TABLE encryption_verifier ADD CONSTRAINT fk_21d142aa3402a788 FOREIGN KEY (encryption_generation_id) REFERENCES encryption_generations (id) ON DELETE RESTRICT;

ALTER TABLE authorities ADD CONSTRAINT fk_40e34b3cb16be22b FOREIGN KEY (management_parent_id) REFERENCES authorities (id) ON DELETE RESTRICT;

ALTER TABLE authorities ADD CONSTRAINT fk_669162f8a872f7dc FOREIGN KEY (issuance_certificate_id) REFERENCES ca_certificates (certificate_id) ON DELETE RESTRICT;

ALTER TABLE ca_key_generations ADD CONSTRAINT fk_92dcbe9ab690c540 FOREIGN KEY (authority_id) REFERENCES authorities (id) ON DELETE RESTRICT;

ALTER TABLE ca_key_generations ADD CONSTRAINT fk_01ba3db5dee8c513 FOREIGN KEY (key_material_id) REFERENCES key_materials (id) ON DELETE RESTRICT;

ALTER TABLE certificates ADD CONSTRAINT fk_7f83dce58104b7df FOREIGN KEY (key_material_id) REFERENCES key_materials (id) ON DELETE RESTRICT;

ALTER TABLE certificates ADD CONSTRAINT fk_e9e2e82a98988902 FOREIGN KEY (issuer_ca_key_generation_id) REFERENCES ca_key_generations (id) ON DELETE RESTRICT;

ALTER TABLE certificates ADD CONSTRAINT fk_13dff2c5ed3b0b95 FOREIGN KEY (created_by) REFERENCES accounts (id) ON DELETE RESTRICT;

ALTER TABLE ca_certificates ADD CONSTRAINT fk_d2974ab287d58426 FOREIGN KEY (certificate_id) REFERENCES certificates (id) ON DELETE RESTRICT;

ALTER TABLE ca_certificates ADD CONSTRAINT fk_7706cb9669c27af5 FOREIGN KEY (ca_key_generation_id) REFERENCES ca_key_generations (id) ON DELETE RESTRICT;

ALTER TABLE ca_certificates ADD CONSTRAINT fk_6eaebfb4c4b9e8d7 FOREIGN KEY (issuer_ca_certificate_id) REFERENCES ca_certificates (certificate_id) ON DELETE RESTRICT;

ALTER TABLE leaf_series ADD CONSTRAINT fk_cd8f0b84f1f5818a FOREIGN KEY (management_authority_id) REFERENCES authorities (id) ON DELETE RESTRICT;

ALTER TABLE leaf_series ADD CONSTRAINT fk_a039adb9ab8e20fd FOREIGN KEY (current_certificate_id) REFERENCES leaf_certificates (certificate_id) ON DELETE RESTRICT;

ALTER TABLE leaf_series ADD CONSTRAINT fk_f00f609bc85a8b2d FOREIGN KEY (current_key_generation_id) REFERENCES leaf_key_generations (id) ON DELETE RESTRICT;

ALTER TABLE leaf_key_generations ADD CONSTRAINT fk_a0bff3f43b8a5b2c FOREIGN KEY (series_id) REFERENCES leaf_series (id) ON DELETE RESTRICT;

ALTER TABLE leaf_key_generations ADD CONSTRAINT fk_b956800452f0b2eb FOREIGN KEY (key_material_id) REFERENCES key_materials (id) ON DELETE RESTRICT;

ALTER TABLE leaf_certificates ADD CONSTRAINT fk_06384169cfcf90e0 FOREIGN KEY (certificate_id) REFERENCES certificates (id) ON DELETE RESTRICT;

ALTER TABLE leaf_certificates ADD CONSTRAINT fk_2c23ed3f17a64b62 FOREIGN KEY (series_id) REFERENCES leaf_series (id) ON DELETE RESTRICT;

ALTER TABLE leaf_certificates ADD CONSTRAINT fk_c12ce3ed779f5610 FOREIGN KEY (leaf_key_generation_id) REFERENCES leaf_key_generations (id) ON DELETE RESTRICT;

ALTER TABLE leaf_certificates ADD CONSTRAINT fk_11424d1d85f3cd68 FOREIGN KEY (issuer_ca_certificate_id) REFERENCES ca_certificates (certificate_id) ON DELETE RESTRICT;

ALTER TABLE leaf_certificates ADD CONSTRAINT fk_5fd286bf59aa192b FOREIGN KEY (previous_certificate_id) REFERENCES leaf_certificates (certificate_id) ON DELETE RESTRICT;

ALTER TABLE certificate_sans ADD CONSTRAINT fk_3dd180cba54052e2 FOREIGN KEY (certificate_id) REFERENCES certificates (id) ON DELETE RESTRICT;

ALTER TABLE key_deliveries ADD CONSTRAINT fk_8625a62d8dba3f63 FOREIGN KEY (leaf_key_generation_id) REFERENCES leaf_key_generations (id) ON DELETE RESTRICT;

ALTER TABLE key_deliveries ADD CONSTRAINT fk_9e815ee2985f87bc FOREIGN KEY (certificate_id) REFERENCES leaf_certificates (certificate_id) ON DELETE RESTRICT;

ALTER TABLE download_tokens ADD CONSTRAINT fk_4e10f12e54112571 FOREIGN KEY (certificate_id) REFERENCES leaf_certificates (certificate_id) ON DELETE RESTRICT;

ALTER TABLE download_tokens ADD CONSTRAINT fk_af012fbc51450c33 FOREIGN KEY (key_delivery_id) REFERENCES key_deliveries (id) ON DELETE RESTRICT;

ALTER TABLE download_tokens ADD CONSTRAINT fk_f6dc38f9df1a7ec9 FOREIGN KEY (created_by) REFERENCES accounts (id) ON DELETE RESTRICT;

ALTER TABLE operation_requests ADD CONSTRAINT fk_b7e02411c951d316 FOREIGN KEY (result_certificate_id) REFERENCES certificates (id) ON DELETE RESTRICT;

ALTER TABLE import_batches ADD CONSTRAINT fk_3b3ec1b8afc062a0 FOREIGN KEY (requested_by) REFERENCES accounts (id) ON DELETE RESTRICT;

ALTER TABLE revocations ADD CONSTRAINT fk_36067d12193f8c36 FOREIGN KEY (issuer_ca_key_generation_id) REFERENCES ca_key_generations (id) ON DELETE RESTRICT;

ALTER TABLE revocations ADD CONSTRAINT fk_668fbf5b4dedf325 FOREIGN KEY (certificate_id) REFERENCES certificates (id) ON DELETE RESTRICT;

ALTER TABLE revocation_revisions ADD CONSTRAINT fk_9dfac914245688ca FOREIGN KEY (revocation_id) REFERENCES revocations (id) ON DELETE RESTRICT;

ALTER TABLE revocation_revisions ADD CONSTRAINT fk_5514a177ef04f226 FOREIGN KEY (actor_id) REFERENCES accounts (id) ON DELETE RESTRICT;

ALTER TABLE revocation_revisions ADD CONSTRAINT fk_7c34967143c7bf81 FOREIGN KEY (source_import_id) REFERENCES import_batches (id) ON DELETE RESTRICT;

ALTER TABLE ca_takeovers ADD CONSTRAINT fk_42c771c10f6c00f4 FOREIGN KEY (ca_key_generation_id) REFERENCES ca_key_generations (id) ON DELETE RESTRICT;

ALTER TABLE ca_takeovers ADD CONSTRAINT fk_271ee9119f023bc4 FOREIGN KEY (confirmed_by) REFERENCES accounts (id) ON DELETE RESTRICT;

ALTER TABLE crl_states ADD CONSTRAINT fk_3b8675b9586b8584 FOREIGN KEY (ca_key_generation_id) REFERENCES ca_key_generations (id) ON DELETE RESTRICT;

ALTER TABLE crl_states ADD CONSTRAINT fk_8c4b1ead8ce0c52b FOREIGN KEY (published_crl_id) REFERENCES crl_documents (id) ON DELETE RESTRICT;

ALTER TABLE crl_states ADD CONSTRAINT fk_d9ef59417b627d3b FOREIGN KEY (signing_ca_certificate_id) REFERENCES ca_certificates (certificate_id) ON DELETE RESTRICT;

ALTER TABLE crl_documents ADD CONSTRAINT fk_8a145d79a7a69099 FOREIGN KEY (ca_key_generation_id) REFERENCES ca_key_generations (id) ON DELETE RESTRICT;

ALTER TABLE crl_documents ADD CONSTRAINT fk_c31c97c7dc4fb6de FOREIGN KEY (source_import_id) REFERENCES import_batches (id) ON DELETE RESTRICT;

ALTER TABLE ca_transitions ADD CONSTRAINT fk_f26514908e99e611 FOREIGN KEY (source_authority_id) REFERENCES authorities (id) ON DELETE RESTRICT;

ALTER TABLE ca_transitions ADD CONSTRAINT fk_48f8f15fcb21dc55 FOREIGN KEY (target_authority_id) REFERENCES authorities (id) ON DELETE RESTRICT;

ALTER TABLE ca_transitions ADD CONSTRAINT fk_ec18d862ee114439 FOREIGN KEY (reported_by) REFERENCES accounts (id) ON DELETE RESTRICT;

ALTER TABLE transition_impacts ADD CONSTRAINT fk_13579f0c61de6da2 FOREIGN KEY (transition_id) REFERENCES ca_transitions (id) ON DELETE RESTRICT;

ALTER TABLE transition_impacts ADD CONSTRAINT fk_62cd53a17ff95231 FOREIGN KEY (certificate_id) REFERENCES certificates (id) ON DELETE RESTRICT;

ALTER TABLE transition_impacts ADD CONSTRAINT fk_a5ab2d2e43b207d2 FOREIGN KEY (replacement_certificate_id) REFERENCES certificates (id) ON DELETE RESTRICT;

ALTER TABLE deployment_confirmations ADD CONSTRAINT fk_3eeaaec4c2e7075a FOREIGN KEY (transition_id) REFERENCES ca_transitions (id) ON DELETE RESTRICT;

ALTER TABLE deployment_confirmations ADD CONSTRAINT fk_a5f7e7ea535212e4 FOREIGN KEY (certificate_id) REFERENCES certificates (id) ON DELETE RESTRICT;

ALTER TABLE deployment_confirmations ADD CONSTRAINT fk_ab1c0a331eafeae1 FOREIGN KEY (confirmed_by) REFERENCES accounts (id) ON DELETE RESTRICT;

ALTER TABLE tls_versions ADD CONSTRAINT fk_d39c076d76798d02 FOREIGN KEY (key_material_id) REFERENCES key_materials (id) ON DELETE RESTRICT;

ALTER TABLE tls_versions ADD CONSTRAINT fk_939d8acf0a6cf0e4 FOREIGN KEY (managed_certificate_id) REFERENCES leaf_certificates (certificate_id) ON DELETE RESTRICT;

ALTER TABLE tls_changes ADD CONSTRAINT fk_cf4e012859ecc8c7 FOREIGN KEY (previous_version_id) REFERENCES tls_versions (id) ON DELETE RESTRICT;

ALTER TABLE tls_changes ADD CONSTRAINT fk_88007c99f5dbcca7 FOREIGN KEY (candidate_version_id) REFERENCES tls_versions (id) ON DELETE RESTRICT;

ALTER TABLE maintenance_crl_requirements ADD CONSTRAINT fk_7c43436d8aad7b50 FOREIGN KEY (maintenance_run_id) REFERENCES maintenance_runs (id) ON DELETE RESTRICT;

ALTER TABLE maintenance_crl_requirements ADD CONSTRAINT fk_07fe1d5c42134a95 FOREIGN KEY (ca_key_generation_id) REFERENCES ca_key_generations (id) ON DELETE RESTRICT;

ALTER TABLE maintenance_crl_requirements ADD CONSTRAINT fk_833e3eb8305242b1 FOREIGN KEY (satisfied_crl_id) REFERENCES crl_documents (id) ON DELETE RESTRICT;

ALTER TABLE installation ADD CONSTRAINT fk_880580b880d4c5c0 FOREIGN KEY (first_admin_id) REFERENCES accounts (id) ON DELETE RESTRICT;

ALTER TABLE installation ADD CONSTRAINT fk_686eed8d14e369c4 FOREIGN KEY (active_encryption_generation_id) REFERENCES encryption_generations (id) ON DELETE RESTRICT;

ALTER TABLE installation ADD CONSTRAINT fk_b2c4347c9d58aec8 FOREIGN KEY (active_tls_version_id) REFERENCES tls_versions (id) ON DELETE RESTRICT;

ALTER TABLE audit_event_scopes ADD CONSTRAINT fk_a026aa649a1fe328 FOREIGN KEY (event_id) REFERENCES audit_events (id) ON DELETE RESTRICT;

ALTER TABLE audit_event_scopes ADD CONSTRAINT fk_0b6ca9f7b2fa06be FOREIGN KEY (authority_id) REFERENCES authorities (id) ON DELETE RESTRICT;

CREATE INDEX ix_certificates_1 ON certificates (not_after,id);

CREATE INDEX ix_certificates_2 ON certificates (issuer_ca_key_generation_id,not_after);

CREATE INDEX ix_certificates_3 ON certificates (key_material_id,id);

CREATE INDEX ix_leaf_certificates_1 ON leaf_certificates (series_id,certificate_id);

CREATE INDEX ix_certificate_sans_1 ON certificate_sans (type,normalized_value_hash);

CREATE INDEX ix_key_deliveries_1 ON key_deliveries (state,expires_at);

CREATE INDEX ix_download_tokens_1 ON download_tokens (key_delivery_id,invalidated_at);

CREATE INDEX ix_download_tokens_2 ON download_tokens (certificate_id,purpose,invalidated_at);

CREATE INDEX ix_download_tokens_3 ON download_tokens (expires_at);

CREATE INDEX ix_sessions_1 ON sessions (account_id,absolute_expires_at);

CREATE INDEX ix_password_reset_tokens_1 ON password_reset_tokens (account_id,expires_at);

CREATE INDEX ix_jobs_1 ON jobs (state,available_at);

CREATE INDEX ix_audit_events_1 ON audit_events (occurred_at,id);

CREATE INDEX ix_audit_events_2 ON audit_events (actor_id,occurred_at);

CREATE INDEX ix_audit_events_3 ON audit_events (client_ip,occurred_at);

CREATE INDEX ix_audit_event_scopes_1 ON audit_event_scopes (authority_id,event_id);

CREATE INDEX ix_crl_documents_1 ON crl_documents (ca_key_generation_id,created_at);

CREATE INDEX ix_revocations_1 ON revocations (certificate_id);

CREATE INDEX ix_ca_takeovers_1 ON ca_takeovers (ca_key_generation_id,state);
