-- Initial unreleased schema, generated by tools/generate_migrations.py.
-- Execute statements under the migration runner exclusive lock.

CREATE TABLE accounts (
    id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    version BIGINT NOT NULL,
    login_name VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    normalized_login_name VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    password_hash LONGTEXT NOT NULL,
    state VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    auth_epoch BIGINT NOT NULL,
    is_global_admin BOOLEAN NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (normalized_login_name),
    CHECK (state IN ('active','reset_pending','disabled')),
    CHECK (length(id) = 36),
    CHECK (version >= 0),
    CHECK (length(login_name) <= 64),
    CHECK (length(normalized_login_name) <= 64),
    CHECK (length(state) <= 32),
    CHECK (auth_epoch >= 0),
    CHECK (is_global_admin IN (0,1))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE sessions (
    id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at BIGINT NOT NULL,
    token_hash VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    account_id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    auth_epoch BIGINT NOT NULL,
    last_seen_at BIGINT NOT NULL,
    absolute_expires_at BIGINT NOT NULL,
    csrf_secret_hash VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (token_hash),
    CHECK (length(id) = 36),
    CHECK (length(token_hash) = 64),
    CHECK (length(account_id) = 36),
    CHECK (auth_epoch >= 0),
    CHECK (length(csrf_secret_hash) = 64)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE password_reset_tokens (
    id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at BIGINT NOT NULL,
    token_hash VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    account_id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    auth_epoch BIGINT NOT NULL,
    expires_at BIGINT NOT NULL,
    consumed_at BIGINT,
    invalidated_at BIGINT,
    PRIMARY KEY (id),
    UNIQUE (token_hash),
    CHECK (length(id) = 36),
    CHECK (length(token_hash) = 64),
    CHECK (length(account_id) = 36),
    CHECK (auth_epoch >= 0)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE auth_rate_limits (
    id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at BIGINT NOT NULL,
    kind VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    subject_hash VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    window_start BIGINT NOT NULL,
    failure_count BIGINT NOT NULL,
    blocked_until BIGINT,
    PRIMARY KEY (id),
    UNIQUE (kind, subject_hash, window_start),
    CHECK (length(id) = 36),
    CHECK (length(kind) <= 32),
    CHECK (length(subject_hash) = 64),
    CHECK (failure_count >= 0)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE service_settings (
    id BIGINT NOT NULL,
    schema_version BIGINT NOT NULL,
    settings_json LONGTEXT NOT NULL,
    updated_at BIGINT NOT NULL,
    version BIGINT NOT NULL,
    updated_by VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin,
    PRIMARY KEY (id),
    CHECK (id = 1),
    CHECK (schema_version >= 0),
    CHECK (version >= 0),
    CHECK (length(updated_by) = 36)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
