-- Initial unreleased schema, generated by tools/generate_migrations.py.
-- Execute statements under the migration runner exclusive lock.

CREATE TABLE key_materials (
    id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at BIGINT NOT NULL,
    spki_sha256 VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    spki_der LONGBLOB NOT NULL,
    algorithm VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    parameters_json LONGTEXT NOT NULL,
    origin VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    compromised_at BIGINT,
    PRIMARY KEY (id),
    UNIQUE (spki_sha256),
    CHECK (origin IN ('generated','imported')),
    CHECK (length(id) = 36),
    CHECK (length(spki_sha256) = 64),
    CHECK (length(algorithm) <= 32),
    CHECK (length(origin) <= 32)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE encryption_generations (
    id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at BIGINT NOT NULL,
    activated_at BIGINT NOT NULL,
    retired_at BIGINT,
    PRIMARY KEY (id),
    CHECK (length(id) = 36)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE private_key_secrets (
    key_material_id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    purpose VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    encryption_generation_id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    format_version BIGINT NOT NULL,
    nonce LONGBLOB NOT NULL,
    ciphertext LONGBLOB NOT NULL,
    PRIMARY KEY (key_material_id),
    CHECK (purpose IN ('ca_signing','leaf_delivery','internal_tls','bootstrap_ca')),
    CHECK (length(nonce) = 12),
    CHECK (length(key_material_id) = 36),
    CHECK (length(purpose) <= 32),
    CHECK (length(encryption_generation_id) = 36),
    CHECK (format_version >= 0)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE encryption_verifier (
    id BIGINT NOT NULL,
    encryption_generation_id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    format_version BIGINT NOT NULL,
    nonce LONGBLOB NOT NULL,
    ciphertext LONGBLOB NOT NULL,
    PRIMARY KEY (id),
    CHECK (id = 1),
    CHECK (length(nonce) = 12),
    CHECK (length(encryption_generation_id) = 36),
    CHECK (format_version >= 0)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
