-- Initial unreleased schema, generated by tools/generate_migrations.py.
-- Execute statements under the migration runner exclusive lock.

CREATE TABLE ca_transitions (
    id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    version BIGINT NOT NULL,
    source_authority_id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    target_authority_id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin,
    mode VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    state VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    reported_by VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    reported_at BIGINT NOT NULL,
    reason LONGTEXT NOT NULL,
    PRIMARY KEY (id),
    CHECK (mode IN ('normal','emergency')),
    CHECK (state IN ('in_progress','externally_completed','closed')),
    CHECK (target_authority_id IS NULL OR target_authority_id <> source_authority_id),
    CHECK (length(id) = 36),
    CHECK (version >= 0),
    CHECK (length(source_authority_id) = 36),
    CHECK (length(target_authority_id) = 36),
    CHECK (length(mode) <= 32),
    CHECK (length(state) <= 32),
    CHECK (length(reported_by) = 36)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE transition_impacts (
    transition_id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    certificate_id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    replacement_certificate_id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin,
    reissued_at BIGINT,
    PRIMARY KEY (transition_id, certificate_id),
    CHECK (length(transition_id) = 36),
    CHECK (length(certificate_id) = 36),
    CHECK (length(replacement_certificate_id) = 36)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE deployment_confirmations (
    id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at BIGINT NOT NULL,
    transition_id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    certificate_id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin,
    target_label LONGTEXT NOT NULL,
    action VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    confirmed_by VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin,
    confirmed_at BIGINT,
    PRIMARY KEY (id),
    CHECK (action IN ('trust_added','certificate_installed','trust_removed')),
    CHECK (length(id) = 36),
    CHECK (length(transition_id) = 36),
    CHECK (length(certificate_id) = 36),
    CHECK (length(action) <= 32),
    CHECK (length(confirmed_by) = 36)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE tls_versions (
    id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at BIGINT NOT NULL,
    source VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    key_material_id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    managed_certificate_id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin,
    leaf_der LONGBLOB NOT NULL,
    chain_bundle LONGBLOB NOT NULL,
    validated_service_url LONGTEXT,
    not_after BIGINT NOT NULL,
    PRIMARY KEY (id),
    CHECK (source IN ('bootstrap','managed','external')),
    CHECK (source = 'bootstrap' OR validated_service_url IS NOT NULL),
    CHECK (length(id) = 36),
    CHECK (length(source) <= 32),
    CHECK (length(key_material_id) = 36),
    CHECK (length(managed_certificate_id) = 36)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE tls_changes (
    id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    version BIGINT NOT NULL,
    previous_version_id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin,
    candidate_version_id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    phase VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    error_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin,
    PRIMARY KEY (id),
    CHECK (phase IN ('prepared','committed','applied','rolled_back','recovery_required')),
    CHECK (length(id) = 36),
    CHECK (version >= 0),
    CHECK (length(previous_version_id) = 36),
    CHECK (length(candidate_version_id) = 36),
    CHECK (length(phase) <= 32),
    CHECK (length(error_code) <= 64)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE maintenance_runs (
    id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    version BIGINT NOT NULL,
    kind VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    phase VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    details_json LONGTEXT NOT NULL,
    started_at BIGINT NOT NULL,
    completed_at BIGINT,
    error_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin,
    PRIMARY KEY (id),
    CHECK (length(id) = 36),
    CHECK (version >= 0),
    CHECK (length(kind) <= 32),
    CHECK (length(phase) <= 32),
    CHECK (length(error_code) <= 64)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE maintenance_crl_requirements (
    maintenance_run_id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    ca_key_generation_id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    minimum_generation BIGINT NOT NULL,
    minimum_number_hex VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    satisfied_crl_id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin,
    PRIMARY KEY (maintenance_run_id, ca_key_generation_id),
    CHECK (length(maintenance_run_id) = 36),
    CHECK (length(ca_key_generation_id) = 36),
    CHECK (minimum_generation >= 0),
    CHECK (length(minimum_number_hex) BETWEEN 1 AND 40),
    CHECK ((length(minimum_number_hex) = 1 OR substr(minimum_number_hex,1,1) <> '0')),
    CHECK (minimum_number_hex REGEXP '^[0-9a-f]+$'),
    CHECK (length(satisfied_crl_id) = 36)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE TABLE jobs (
    id VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    version BIGINT NOT NULL,
    kind VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    dedup_key VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    payload_version BIGINT NOT NULL,
    payload_json LONGTEXT NOT NULL,
    state VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    available_at BIGINT NOT NULL,
    lease_until BIGINT,
    attempt_count BIGINT NOT NULL,
    last_error_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin,
    PRIMARY KEY (id),
    UNIQUE (dedup_key),
    CHECK (state IN ('pending','running','succeeded','failed')),
    CHECK (length(id) = 36),
    CHECK (version >= 0),
    CHECK (length(kind) <= 32),
    CHECK (length(dedup_key) <= 128),
    CHECK (payload_version >= 0),
    CHECK (length(state) <= 32),
    CHECK (attempt_count >= 0),
    CHECK (length(last_error_code) <= 64)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
